version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build all formats like pdf, htmlzip, etc
formats: all

python:
  install:
  - requirements: requirements/docs.txt
